spring:
  jpa:
    defer-datasource-initialization: true
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:eventtimeline
    username: sa
    password: sa
    driverClassName: org.h2.Driver

server:
  error:
    path: /error

jwt:
  secret: $$eTnt-$23tOmE#-DAw14l